import { ReportData } from '../ReportService';
import { logger } from '@/config/logger';
import { ReportFieldMapper } from './ReportFieldMapper';

/**
 * CSV Report Generator
 * Generates CSV format reports from report data
 */
export class CsvReportGenerator {
  /**
   * Generate CSV content from report data
   */
  static async generate(reportData: ReportData): Promise<{ csv?: string; error?: string }> {
    try {
      const { data, metadata, template } = reportData;

      if (!data || data.length === 0) {
        return { csv: this.generateEmptyReport(template.name, metadata) };
      }

      // Generate CSV header and rows using shared mapper
      const headers = ReportFieldMapper.getHeaders(template.template_id);
      const rows = data.map(record => ReportFieldMapper.extractRowData(record, headers));

      // Build CSV content
      const csvLines: string[] = [];

      // Add metadata header
      csvLines.push(`# ${metadata.report_name}`);
      csvLines.push(`# Generated: ${metadata.generated_at.toISOString()}`);
      csvLines.push(`# Generated By: ${metadata.generated_by}`);
      csvLines.push(`# Date Range: ${metadata.date_range.start.toISOString()} to ${metadata.date_range.end.toISOString()}`);
      csvLines.push(`# Total Records: ${metadata.total_records}`);
      csvLines.push('');

      // Add column headers
      csvLines.push(headers.join(','));

      // Add data rows with proper CSV escaping
      rows.forEach(row => {
        const escapedRow = row.map(value => {
          if (typeof value === 'string' && (value.includes(',') || value.includes('"') || value.includes('\n'))) {
            return `"${value.replace(/"/g, '""')}"`;
          }
          return value || '';
        });
        csvLines.push(escapedRow.join(','));
      });

      const csv = csvLines.join('\n');

      logger.info(`CSV report generated: ${template.name} (${data.length} records)`);
      return { csv };
    } catch (error) {
      logger.error('Error generating CSV report:', error);
      return { error: 'Failed to generate CSV report' };
    }
  }



  /**
   * Generate empty report with message
   */
  private static generateEmptyReport(reportName: string, metadata: any): string {
    return [
      `# ${reportName}`,
      `# Generated: ${metadata.generated_at.toISOString()}`,
      `# Generated By: ${metadata.generated_by}`,
      '',
      'No data available for the selected criteria.'
    ].join('\n');
  }

  /**
   * Save CSV to file
   */
  static async saveToFile(csv: string, filename: string): Promise<{ success: boolean; path?: string; error?: string }> {
    try {
      const fs = require('fs').promises;
      const path = require('path');

      const reportsDir = path.join(process.cwd(), 'reports', 'generated');

      // Ensure directory exists
      await fs.mkdir(reportsDir, { recursive: true });

      const filePath = path.join(reportsDir, filename);
      await fs.writeFile(filePath, csv, 'utf8');

      logger.info(`CSV report saved to: ${filePath}`);
      return { success: true, path: filePath };
    } catch (error) {
      logger.error('Error saving CSV report:', error);
      return { success: false, error: 'Failed to save CSV report' };
    }
  }
}

export default CsvReportGenerator;
