import { ReportData } from '../ReportService';
import { logger } from '@/config/logger';

/**
 * PDF Report Generator
 * Generates PDF format reports (simplified version - returns HTML for now)
 *
 * TODO: Integrate with puppeteer or pdfkit for actual PDF generation
 * For now, generates HTML that can be converted to PDF on frontend
 */
export class PdfReportGenerator {
  /**
   * Generate PDF HTML content from report data
   */
  static async generate(reportData: ReportData): Promise<{ html?: string; error?: string }> {
    try {
      const { data, metadata, template } = reportData;

      const html = this.generateHtml(data, metadata, template);

      logger.info(`PDF HTML generated: ${template.name} (${data.length} records)`);
      return { html };
    } catch (error) {
      logger.error('Error generating PDF report:', error);
      return { error: 'Failed to generate PDF report' };
    }
  }

  /**
   * Generate HTML content for PDF
   */
  private static generateHtml(data: any[], metadata: any, template: any): string {
    const styles = this.getStyles();
    const header = this.generateHeader(metadata);
    const table = data.length > 0 ? this.generateTable(data, template.template_id) : '<p class="no-data">No data available for the selected criteria.</p>';
    const footer = this.generateFooter();

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${metadata.report_name}</title>
  <style>${styles}</style>
</head>
<body>
  <div class="container">
    ${header}
    ${table}
    ${footer}
  </div>
</body>
</html>
    `;
  }

  /**
   * CSS styles for PDF
   */
  private static getStyles(): string {
    return `
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      body {
        font-family: 'Arial', sans-serif;
        font-size: 12px;
        line-height: 1.6;
        color: #333;
      }

      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
      }

      .header {
        border-bottom: 3px solid #4472C4;
        padding-bottom: 20px;
        margin-bottom: 30px;
      }

      .header h1 {
        font-size: 24px;
        color: #1F4788;
        margin-bottom: 15px;
      }

      .metadata {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
        background: #f5f5f5;
        padding: 15px;
        border-radius: 5px;
      }

      .metadata-item {
        display: flex;
      }

      .metadata-label {
        font-weight: bold;
        margin-right: 10px;
        color: #555;
      }

      .metadata-value {
        color: #333;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
      }

      th {
        background: #4472C4;
        color: white;
        padding: 12px;
        text-align: left;
        font-weight: bold;
        border: 1px solid #ddd;
      }

      td {
        padding: 10px 12px;
        border: 1px solid #ddd;
      }

      tr:nth-child(even) {
        background: #f9f9f9;
      }

      tr:hover {
        background: #f0f0f0;
      }

      .no-data {
        text-align: center;
        padding: 40px;
        color: #999;
        font-style: italic;
      }

      .footer {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid #ddd;
        text-align: center;
        color: #777;
        font-size: 10px;
      }

      .footer-info {
        margin: 5px 0;
      }

      @media print {
        .container {
          padding: 0;
        }

        body {
          font-size: 10px;
        }

        th, td {
          padding: 8px;
        }
      }
    `;
  }

  /**
   * Generate HTML header
   */
  private static generateHeader(metadata: any): string {
    return `
      <div class="header">
        <h1>${metadata.report_name}</h1>
        <div class="metadata">
          <div class="metadata-item">
            <span class="metadata-label">Generated:</span>
            <span class="metadata-value">${metadata.generated_at.toLocaleString()}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Generated By:</span>
            <span class="metadata-value">${metadata.generated_by}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Date Range:</span>
            <span class="metadata-value">${metadata.date_range.start.toLocaleDateString()} to ${metadata.date_range.end.toLocaleDateString()}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Total Records:</span>
            <span class="metadata-value">${metadata.total_records}</span>
          </div>
        </div>
      </div>
    `;
  }

  /**
   * Generate HTML table
   */
  private static generateTable(data: any[], templateId: string): string {
    const headers = this.getTableHeaders(templateId);
    const rows = data.map(record => this.generateTableRow(record, headers, templateId));

    return `
      <table>
        <thead>
          <tr>
            ${headers.map(h => `<th>${h}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${rows.join('')}
        </tbody>
      </table>
    `;
  }

  /**
   * Generate HTML table row
   */
  private static generateTableRow(record: any, headers: string[], templateId: string): string {
    const cells = headers.map(header => {
      const key = header.toLowerCase().replace(/ /g, '_');
      let value = record[key];

      // Handle nested objects
      if (typeof value === 'object' && value !== null) {
        if (value.name) value = value.name;
        else if (value.email) value = value.email;
        else if (value instanceof Date) value = value.toLocaleDateString();
        else value = JSON.stringify(value);
      }

      // Format dates
      if (value instanceof Date) {
        value = value.toLocaleDateString();
      }

      // Format currency
      if (header.includes('Pay') || header.includes('Revenue') || header.includes('Cost') || header.includes('Profit')) {
        if (typeof value === 'number') {
          value = `$${value.toFixed(2)}`;
        }
      }

      // Format percentages
      if (header.includes('%') && typeof value === 'number') {
        value = `${(value * 100).toFixed(2)}%`;
      }

      return `<td>${value || '-'}</td>`;
    });

    return `<tr>${cells.join('')}</tr>`;
  }

  /**
   * Get table headers based on template
   */
  private static getTableHeaders(templateId: string): string[] {
    const headerMap: Record<string, string[]> = {
      'employee-payslip': ['Month', 'Year', 'Total Hours', 'Billable Hours', 'Hourly Rate', 'Gross Pay', 'Deductions', 'Net Pay'],
      'employee-timesheet-summary': ['Week Start', 'Week End', 'Total Hours', 'Status', 'Submitted At'],
      'employee-performance': ['Period', 'Total Hours', 'Projects', 'Tasks Completed', 'Productivity Score'],
      'employee-attendance': ['Date', 'Hours Worked', 'Status', 'Leave Type'],
      'lead-team-timesheet': ['Employee', 'Email', 'Week Start', 'Total Hours', 'Status'],
      'lead-team-performance': ['Employee', 'Total Hours', 'Projects', 'Productivity Score'],
      'lead-team-attendance': ['Employee', 'Present Days', 'Absent Days', 'Leave Days'],
      'manager-project-performance': ['Project', 'Client', 'Status', 'Budget', 'Hours Spent', 'Utilization %'],
      'manager-project-financial': ['Project', 'Revenue', 'Cost', 'Margin', 'ROI %'],
      'manager-resource-allocation': ['Employee', 'Allocated Hours', 'Utilization %'],
      'manager-team-billing': ['Employee', 'Billable Hours', 'Revenue', 'Rate'],
      'management-financial-dashboard': ['Period', 'Revenue', 'Cost', 'Profit', 'Margin %'],
      'management-org-utilization': ['Department', 'Employees', 'Utilization %'],
      'management-client-billing': ['Client', 'Projects', 'Revenue', 'Hours Billed'],
      'management-workforce-analytics': ['Department', 'Employees', 'Total Hours', 'Productivity'],
      'management-portfolio-analysis': ['Project', 'Status', 'Budget', 'Timeline'],
      'admin-audit-logs': ['Date', 'User', 'Action', 'Entity', 'Details'],
      'admin-user-access': ['User', 'Email', 'Role', 'Status', 'Last Login'],
      'default': ['ID', 'Name', 'Value', 'Status', 'Date']
    };

    return headerMap[templateId] || headerMap['default'];
  }

  /**
   * Generate HTML footer
   */
  private static generateFooter(): string {
    return `
      <div class="footer">
        <div class="footer-info">This report is confidential and generated for authorized personnel only.</div>
        <div class="footer-info">Generated by ES-TM Timesheet Management System</div>
        <div class="footer-info">© ${new Date().getFullYear()} All Rights Reserved</div>
      </div>
    `;
  }

  /**
   * Save HTML to file
   */
  static async saveToFile(html: string, filename: string): Promise<{ success: boolean; path?: string; error?: string }> {
    try {
      const fs = require('fs').promises;
      const path = require('path');

      const reportsDir = path.join(process.cwd(), 'reports', 'generated');
      await fs.mkdir(reportsDir, { recursive: true });

      const filePath = path.join(reportsDir, filename);
      await fs.writeFile(filePath, html, 'utf8');

      logger.info(`PDF HTML saved to: ${filePath}`);
      return { success: true, path: filePath };
    } catch (error) {
      logger.error('Error saving PDF HTML:', error);
      return { success: false, error: 'Failed to save PDF HTML' };
    }
  }
}

export default PdfReportGenerator;
