import { ReportData } from '../ReportService';
import { logger } from '@/config/logger';
import puppeteer from 'puppeteer';
import { ReportFieldMapper } from './ReportFieldMapper';

/**
 * PDF Report Generator
 * Generates PDF format reports using puppeteer
 */
export class PdfReportGenerator {
  /**
   * Generate PDF buffer from report data
   */
  static async generate(reportData: ReportData): Promise<{ buffer?: Buffer; error?: string }> {
    try {
      const { data, metadata, template } = reportData;

      // Generate HTML content
      const html = this.generateHtml(data, metadata, template);

      // Convert HTML to PDF using puppeteer
      const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });

      try {
        const page = await browser.newPage();
        await page.setContent(html, { waitUntil: 'networkidle0' });
        
        const pdfBuffer = await page.pdf({
          format: 'A4',
          margin: {
            top: '20mm',
            right: '15mm',
            bottom: '20mm',
            left: '15mm'
          },
          printBackground: true
        });

        await browser.close();

        logger.info(`PDF report generated: ${template.name} (${data.length} records)`);
        return { buffer: Buffer.from(pdfBuffer) };
      } catch (pdfError) {
        await browser.close();
        throw pdfError;
      }
    } catch (error) {
      logger.error('Error generating PDF report:', error);
      return { error: 'Failed to generate PDF report' };
    }
  }

  /**
   * Generate HTML content for PDF
   */
  private static generateHtml(data: any[], metadata: any, template: any): string {
    const styles = this.getStyles();
    const header = this.generateHeader(metadata);
    const table = data.length > 0 ? this.generateTable(data, template.template_id) : '<p class="no-data">No data available for the selected criteria.</p>';
    const footer = this.generateFooter();

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${metadata.report_name}</title>
  <style>${styles}</style>
</head>
<body>
  <div class="container">
    ${header}
    ${table}
    ${footer}
  </div>
</body>
</html>
    `;
  }

  /**
   * CSS styles for PDF
   */
  private static getStyles(): string {
    return `
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      body {
        font-family: 'Arial', sans-serif;
        font-size: 12px;
        line-height: 1.6;
        color: #333;
      }

      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
      }

      .header {
        border-bottom: 3px solid #4472C4;
        padding-bottom: 20px;
        margin-bottom: 30px;
      }

      .header h1 {
        font-size: 24px;
        color: #1F4788;
        margin-bottom: 15px;
      }

      .metadata {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
        background: #f5f5f5;
        padding: 15px;
        border-radius: 5px;
      }

      .metadata-item {
        display: flex;
      }

      .metadata-label {
        font-weight: bold;
        margin-right: 10px;
        color: #555;
      }

      .metadata-value {
        color: #333;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
      }

      th {
        background: #4472C4;
        color: white;
        padding: 12px;
        text-align: left;
        font-weight: bold;
        border: 1px solid #ddd;
      }

      td {
        padding: 10px 12px;
        border: 1px solid #ddd;
      }

      tr:nth-child(even) {
        background: #f9f9f9;
      }

      tr:hover {
        background: #f0f0f0;
      }

      .no-data {
        text-align: center;
        padding: 40px;
        color: #999;
        font-style: italic;
      }

      .footer {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid #ddd;
        text-align: center;
        color: #777;
        font-size: 10px;
      }

      .footer-info {
        margin: 5px 0;
      }

      @media print {
        .container {
          padding: 0;
        }

        body {
          font-size: 10px;
        }

        th, td {
          padding: 8px;
        }
      }
    `;
  }

  /**
   * Generate HTML header
   */
  private static generateHeader(metadata: any): string {
    return `
      <div class="header">
        <h1>${metadata.report_name}</h1>
        <div class="metadata">
          <div class="metadata-item">
            <span class="metadata-label">Generated:</span>
            <span class="metadata-value">${metadata.generated_at.toLocaleString()}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Generated By:</span>
            <span class="metadata-value">${metadata.generated_by}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Date Range:</span>
            <span class="metadata-value">${metadata.date_range.start.toLocaleDateString()} to ${metadata.date_range.end.toLocaleDateString()}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Total Records:</span>
            <span class="metadata-value">${metadata.total_records}</span>
          </div>
        </div>
      </div>
    `;
  }

  /**
   * Generate HTML table
   */
  private static generateTable(data: any[], templateId: string): string {
    const headers = ReportFieldMapper.getHeaders(templateId);
    
    // Debug logging
    if (data.length > 0) {
      logger.info(`PDF Table Generation - Sample data keys: ${JSON.stringify(Object.keys(data[0]))}`);
    }
    
    const rows = data.map(record => {
      const rowData = ReportFieldMapper.extractRowData(record, headers);
      return `<tr>${rowData.map(cell => `<td>${cell}</td>`).join('')}</tr>`;
    });

    return `
      <table>
        <thead>
          <tr>
            ${headers.map(h => `<th>${h}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${rows.join('')}
        </tbody>
      </table>
    `;
  }





  /**
   * Generate HTML footer
   */
  private static generateFooter(): string {
    return `
      <div class="footer">
        <div class="footer-info">This report is confidential and generated for authorized personnel only.</div>
        <div class="footer-info">Generated by ES-TM Timesheet Management System</div>
        <div class="footer-info">© ${new Date().getFullYear()} All Rights Reserved</div>
      </div>
    `;
  }

  /**
   * Save HTML to file
   */
  static async saveToFile(html: string, filename: string): Promise<{ success: boolean; path?: string; error?: string }> {
    try {
      const fs = require('fs').promises;
      const path = require('path');

      const reportsDir = path.join(process.cwd(), 'reports', 'generated');
      await fs.mkdir(reportsDir, { recursive: true });

      const filePath = path.join(reportsDir, filename);
      await fs.writeFile(filePath, html, 'utf8');

      logger.info(`PDF HTML saved to: ${filePath}`);
      return { success: true, path: filePath };
    } catch (error) {
      logger.error('Error saving PDF HTML:', error);
      return { success: false, error: 'Failed to save PDF HTML' };
    }
  }
}

export default PdfReportGenerator;
